from arpeggio import Terminal as Terminal
from typing import Any

class Exporter:
    def __init__(self) -> None: ...
    def export(self, obj: Any): ...
    def exportFile(self, obj: Any, file_name: Any) -> None: ...

class ExportAdapter:
    adaptee: Any = ...
    export: Any = ...
    def __init__(self, node: Any, export: Any) -> None: ...

class DOTExportAdapter(ExportAdapter):
    @property
    def id(self) -> None: ...
    @property
    def desc(self) -> None: ...
    @property
    def neighbours(self) -> None: ...

class PMDOTExportAdapter(DOTExportAdapter):
    @property
    def id(self): ...
    @property
    def desc(self): ...
    @property
    def neighbours(self): ...

class PTDOTExportAdapter(PMDOTExportAdapter):
    @property
    def neighbours(self): ...

class DOTExporter(Exporter): ...

class PMDOTExporter(DOTExporter):
    def export(self, obj: Any): ...
    def exportFile(self, obj: Any, file_name: Any): ...

class PTDOTExporter(DOTExporter):
    def export(self, obj: Any): ...
    def exportFile(self, obj: Any, file_name: Any): ...
